[INFO] [2020-10-29 08:26:06,099] [2750:140391119148864] - task_executor.py[line:121]: run 2020102908260459230210 dataio_0 2020102908260459230210_dataio_0 guest 10000 task
[INFO] [2020-10-29 08:26:06,100] [2750:140391119148864] - task_executor.py[line:122]: {'DataIOParam': {'input_format': 'dense', 'delimitor': ',', 'data_type': 'float64', 'exclusive_data_type': None, 'tag_with_value': False, 'tag_value_delimitor': ':', 'missing_fill': False, 'default_value': 0, 'missing_fill_method': None, 'missing_impute': None, 'outlier_replace': False, 'outlier_replace_method': None, 'outlier_impute': None, 'outlier_replace_value': 0, 'with_label': True, 'label_name': 'y', 'label_type': 'int', 'output_format': 'dense'}, 'initiator': {'role': 'guest', 'party_id': 10000}, 'job_parameters': {'work_mode': 0, 'model_id': 'arbiter-10000#guest-10000#host-10000#model', 'model_version': '202010290812019279649'}, 'role': {'guest': [10000], 'host': [10000], 'arbiter': [10000]}, 'config': '/fate/examples/federatedml-1.x-examples/homo_logistic_regression/test_homolr_evaluate_job_conf.json', 'dsl': 'examples/federatedml-1.x-examples/homo_logistic_regression/test_homolr_evaluate_job_dsl.json', 'function': 'submit_job', 'local': {'role': 'guest', 'party_id': 10000}, 'CodePath': 'federatedml/util/data_io.py/DataIO', 'module': 'DataIO'}
[INFO] [2020-10-29 08:26:06,100] [2750:140391119148864] - task_executor.py[line:123]: {'model': ['pipeline.dataio_0.dataio'], 'data': {'data': ['args.eval_data']}}
[INFO] [2020-10-29 08:26:06,116] [2750:140391119148864] - pipelined_model.py[line:177]: parse DataIOMeta proto object normal
[INFO] [2020-10-29 08:26:06,118] [2750:140391119148864] - pipelined_model.py[line:177]: parse DataIOParam proto object normal
[DEBUG] [2020-10-29 08:26:06,119] [2750:140391119148864] - profile_util.py[line:34]: task_executor.py:187 call table, takes 0.0008230209350585938s
[INFO] [2020-10-29 08:26:06,119] [2750:140391119148864] - task_executor.py[line:202]: start save as task 2020102908260459230210_dataio_0 input data table experiment breast_homo_guest
[DEBUG] [2020-10-29 08:26:06,120] [2750:140391119148864] - profile_util.py[line:34]: session.py:178 call collect, takes 0.0008394718170166016s
[DEBUG] [2020-10-29 08:26:06,145] [2750:140391119148864] - profile_util.py[line:34]: task_executor.py:212 call save_as, takes 0.024346590042114258s
[INFO] [2020-10-29 08:26:06,149] [2750:140391119148864] - task_executor.py[line:218]: save as task 2020102908260459230210_dataio_0 input data table to 2020102908260459230210_dataio_0_guest_10000 breast_homo_guest done
[DEBUG] [2020-10-29 08:26:06,390] [2750:140391119148864] - component_properties.py[line:67]: {'DataIOParam': {'input_format': 'dense', 'delimitor': ',', 'data_type': 'float64', 'exclusive_data_type': None, 'tag_with_value': False, 'tag_value_delimitor': ':', 'missing_fill': False, 'default_value': 0, 'missing_fill_method': None, 'missing_impute': None, 'outlier_replace': False, 'outlier_replace_method': None, 'outlier_impute': None, 'outlier_replace_value': 0, 'with_label': True, 'label_name': 'y', 'label_type': 'int', 'output_format': 'dense'}, 'initiator': {'role': 'guest', 'party_id': 10000}, 'job_parameters': {'work_mode': 0, 'model_id': 'arbiter-10000#guest-10000#host-10000#model', 'model_version': '202010290812019279649'}, 'role': {'guest': [10000], 'host': [10000], 'arbiter': [10000]}, 'config': '/fate/examples/federatedml-1.x-examples/homo_logistic_regression/test_homolr_evaluate_job_conf.json', 'dsl': 'examples/federatedml-1.x-examples/homo_logistic_regression/test_homolr_evaluate_job_dsl.json', 'function': 'submit_job', 'local': {'role': 'guest', 'party_id': 10000}, 'CodePath': 'federatedml/util/data_io.py/DataIO', 'module': 'DataIO'}
[DEBUG] [2020-10-29 08:26:06,391] [2750:140391119148864] - component_properties.py[line:74]: need_run: True, need_cv: False
[DEBUG] [2020-10-29 08:26:06,391] [2750:140391119148864] - component_properties.py[line:118]: has_train_data: False, has_eval_data: False, has_normal_data: True
[DEBUG] [2020-10-29 08:26:06,393] [2750:140391119148864] - profile_util.py[line:34]: component_properties.py:155 call count, takes 0.0017688274383544922s
[DEBUG] [2020-10-29 08:26:06,393] [2750:140391119148864] - model_base.py[line:210]: In extract_data, data input: {'args.data': <arch.api.impl.based_1x.table.DTable object at 0x7faa40a07b70>}
[DEBUG] [2020-10-29 08:26:06,393] [2750:140391119148864] - model_base.py[line:87]: func: <bound method DataIO.transform of <federatedml.util.data_io.DataIO object at 0x7faa40a07668>>
[INFO] [2020-10-29 08:26:06,393] [2750:140391119148864] - data_io.py[line:141]: start to read dense data and change data to instance
[DEBUG] [2020-10-29 08:26:06,394] [2750:140391119148864] - profile_util.py[line:34]: abnormal_detection.py:23 call count, takes 0.0007340908050537109s
[DEBUG] [2020-10-29 08:26:06,395] [2750:140391119148864] - data_io.py[line:95]: header is y,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,x24,x25,x26,x27,x28,x29
[DEBUG] [2020-10-29 08:26:06,395] [2750:140391119148864] - data_io.py[line:96]: sid_name is id
[DEBUG] [2020-10-29 08:26:06,440] [2750:140391119148864] - profile_util.py[line:34]: data_io.py:155 call mapValues, takes 0.04513239860534668s
[DEBUG] [2020-10-29 08:26:06,459] [2750:140391119148864] - profile_util.py[line:34]: data_io.py:158 call mapValues, takes 0.01770615577697754s
[DEBUG] [2020-10-29 08:26:06,464] [2750:140391119148864] - profile_util.py[line:34]: io_check.py:29 call count, takes 0.004812479019165039s
[DEBUG] [2020-10-29 08:26:06,489] [2750:140391119148864] - profile_util.py[line:34]: data_io.py:241 call join, takes 0.025113582611083984s
[DEBUG] [2020-10-29 08:26:06,495] [2750:140391119148864] - profile_util.py[line:34]: io_check.py:35 call count, takes 0.005267620086669922s
[DEBUG] [2020-10-29 08:26:06,495] [2750:140391119148864] - io_check.py[line:36]: num row of input: 227 -> num row of output: 227
[DEBUG] [2020-10-29 08:26:06,495] [2750:140391119148864] - model_base.py[line:99]: saved_result is : [<arch.api.impl.based_1x.table.DTable object at 0x7f41389e9748>], data_output: <arch.api.impl.based_1x.table.DTable object at 0x7f41389e9748>
[DEBUG] [2020-10-29 08:26:06,530] [2750:140391119148864] - profile_util.py[line:34]: tracking_manager.py:201 call save_as, takes 0.03481125831604004s
[DEBUG] [2020-10-29 08:26:06,535] [2750:140391119148864] - profile_util.py[line:34]: session.py:178 call collect, takes 0.0014030933380126953s
[DEBUG] [2020-10-29 08:26:06,627] [2750:140391119148864] - profile_util.py[line:34]: tracking_manager.py:221 call count, takes 0.021712064743041992s
[INFO] [2020-10-29 08:26:06,636] [2750:140391119148864] - pipelined_model.py[line:72]: Save dataio_0 default DataIOMeta buffer
[INFO] [2020-10-29 08:26:06,636] [2750:140391119148864] - pipelined_model.py[line:72]: Save dataio_0 default DataIOParam buffer
[INFO] [2020-10-29 08:26:06,648] [2750:140391119148864] - pipelined_model.py[line:77]: Save dataio_0 default successfully
[INFO] [2020-10-29 08:26:06,675] [2750:140391119148864] - task_executor.py[line:160]: task 2020102908260459230210_dataio_0 guest 10000 start time: 2020-10-29 08:26:05
[INFO] [2020-10-29 08:26:06,675] [2750:140391119148864] - task_executor.py[line:161]: task 2020102908260459230210_dataio_0 guest 10000 end time: 2020-10-29 08:26:06
[INFO] [2020-10-29 08:26:06,675] [2750:140391119148864] - task_executor.py[line:162]: task 2020102908260459230210_dataio_0 guest 10000 takes 0.813s
[INFO] [2020-10-29 08:26:06,676] [2750:140391119148864] - task_executor.py[line:164]: finish 2020102908260459230210 dataio_0 2020102908260459230210_dataio_0 guest 10000 success task
