[DEBUG] [2020-10-29 08:26:06,119] [2750:140391119148864] - profile_util.py[line:34]: task_executor.py:187 call table, takes 0.0008230209350585938s
[DEBUG] [2020-10-29 08:26:06,120] [2750:140391119148864] - profile_util.py[line:34]: session.py:178 call collect, takes 0.0008394718170166016s
[DEBUG] [2020-10-29 08:26:06,145] [2750:140391119148864] - profile_util.py[line:34]: task_executor.py:212 call save_as, takes 0.024346590042114258s
[DEBUG] [2020-10-29 08:26:06,393] [2750:140391119148864] - profile_util.py[line:34]: component_properties.py:155 call count, takes 0.0017688274383544922s
[DEBUG] [2020-10-29 08:26:06,394] [2750:140391119148864] - profile_util.py[line:34]: abnormal_detection.py:23 call count, takes 0.0007340908050537109s
[DEBUG] [2020-10-29 08:26:06,440] [2750:140391119148864] - profile_util.py[line:34]: data_io.py:155 call mapValues, takes 0.04513239860534668s
[DEBUG] [2020-10-29 08:26:06,459] [2750:140391119148864] - profile_util.py[line:34]: data_io.py:158 call mapValues, takes 0.01770615577697754s
[DEBUG] [2020-10-29 08:26:06,464] [2750:140391119148864] - profile_util.py[line:34]: io_check.py:29 call count, takes 0.004812479019165039s
[DEBUG] [2020-10-29 08:26:06,489] [2750:140391119148864] - profile_util.py[line:34]: data_io.py:241 call join, takes 0.025113582611083984s
[DEBUG] [2020-10-29 08:26:06,495] [2750:140391119148864] - profile_util.py[line:34]: io_check.py:35 call count, takes 0.005267620086669922s
[DEBUG] [2020-10-29 08:26:06,530] [2750:140391119148864] - profile_util.py[line:34]: tracking_manager.py:201 call save_as, takes 0.03481125831604004s
[DEBUG] [2020-10-29 08:26:06,535] [2750:140391119148864] - profile_util.py[line:34]: session.py:178 call collect, takes 0.0014030933380126953s
[DEBUG] [2020-10-29 08:26:06,627] [2750:140391119148864] - profile_util.py[line:34]: tracking_manager.py:221 call count, takes 0.021712064743041992s
