[DEBUG] [2020-10-29 08:12:03,493] [2470:140117390411584] - profile_util.py[line:34]: task_executor.py:187 call table, takes 0.0009226799011230469s
[DEBUG] [2020-10-29 08:12:03,495] [2470:140117390411584] - profile_util.py[line:34]: session.py:178 call collect, takes 0.0008995532989501953s
[DEBUG] [2020-10-29 08:12:03,519] [2470:140117390411584] - profile_util.py[line:34]: task_executor.py:212 call save_as, takes 0.02379631996154785s
[DEBUG] [2020-10-29 08:12:03,802] [2470:140117390411584] - profile_util.py[line:34]: component_properties.py:155 call count, takes 0.0013017654418945312s
[DEBUG] [2020-10-29 08:12:03,803] [2470:140117390411584] - profile_util.py[line:34]: abnormal_detection.py:23 call count, takes 0.00040459632873535156s
[DEBUG] [2020-10-29 08:12:03,845] [2470:140117390411584] - profile_util.py[line:34]: data_io.py:155 call mapValues, takes 0.04158592224121094s
[DEBUG] [2020-10-29 08:12:03,862] [2470:140117390411584] - profile_util.py[line:34]: data_io.py:158 call mapValues, takes 0.016089677810668945s
[DEBUG] [2020-10-29 08:12:03,885] [2470:140117390411584] - profile_util.py[line:34]: data_io.py:241 call join, takes 0.022542715072631836s
[DEBUG] [2020-10-29 08:12:03,922] [2470:140117390411584] - profile_util.py[line:34]: tracking_manager.py:201 call save_as, takes 0.03666090965270996s
[DEBUG] [2020-10-29 08:12:03,925] [2470:140117390411584] - profile_util.py[line:34]: session.py:178 call collect, takes 0.0009868144989013672s
[DEBUG] [2020-10-29 08:12:03,981] [2470:140117390411584] - profile_util.py[line:34]: tracking_manager.py:221 call count, takes 0.01641058921813965s
