[DEBUG] [2020-10-29 08:04:50,357] [1430:140352438318912] - component_properties.py[line:67]: {'DataIOParam': {'input_format': 'dense', 'delimitor': ',', 'data_type': 'float64', 'exclusive_data_type': None, 'tag_with_value': False, 'tag_value_delimitor': ':', 'missing_fill': False, 'default_value': 0, 'missing_fill_method': None, 'missing_impute': None, 'outlier_replace': False, 'outlier_replace_method': None, 'outlier_impute': None, 'outlier_replace_value': 0, 'with_label': False, 'label_name': 'y', 'label_type': 'int', 'output_format': 'dense'}, 'initiator': {'role': 'guest', 'party_id': 9999}, 'job_parameters': {'work_mode': 0, 'processors_per_node': 1, 'align_task_input_data_partition': True, 'model_id': 'arbiter-10000#guest-9999#host-10000#model', 'model_version': '202010290804483462984'}, 'role': {'guest': [9999], 'host': [10000], 'arbiter': [10000]}, 'local': {'role': 'host', 'party_id': 10000}, 'CodePath': 'federatedml/util/data_io.py/DataIO', 'module': 'DataIO'}
[DEBUG] [2020-10-29 08:04:50,357] [1430:140352438318912] - component_properties.py[line:74]: need_run: True, need_cv: False
[DEBUG] [2020-10-29 08:04:50,358] [1430:140352438318912] - component_properties.py[line:118]: has_train_data: False, has_eval_data: False, has_normal_data: True
[DEBUG] [2020-10-29 08:04:50,358] [1430:140352438318912] - model_base.py[line:210]: In extract_data, data input: {'args.data': <arch.api.impl.based_1x.table.DTable object at 0x7fa13f127ba8>}
[DEBUG] [2020-10-29 08:04:50,359] [1430:140352438318912] - model_base.py[line:87]: func: <bound method DataIO.fit of <federatedml.util.data_io.DataIO object at 0x7fa13f1271d0>>
[INFO] [2020-10-29 08:04:50,359] [1430:140352438318912] - data_io.py[line:141]: start to read dense data and change data to instance
[DEBUG] [2020-10-29 08:04:50,361] [1430:140352438318912] - data_io.py[line:95]: header is x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19
[DEBUG] [2020-10-29 08:04:50,361] [1430:140352438318912] - data_io.py[line:96]: sid_name is id
[DEBUG] [2020-10-29 08:04:50,432] [1430:140352438318912] - model_base.py[line:99]: saved_result is : [<arch.api.impl.based_1x.table.DTable object at 0x7f71bb71bc50>], data_output: <arch.api.impl.based_1x.table.DTable object at 0x7f71bb71bc50>
